export default {
  ARTIST_FIRSTNAME: "firstName",
  ARTIST_LASTNAME: "lastName",
  ARTIST_USERNAME: "username",
  ARTIST_DISPLAYNAME: "displayName",
  ARTIST_LOCATION: "location",
  ARTIST_EMAIL: "email",
  ARTIST_PHONE: "phone",
  ARTIST_ABOUT: "about",
  ARTIST_ARTTYPE: "artType",
  UPDATE_ARTIST_SCREEN_USER: "artist",
  UPDATE_ARTIST_SCREEN_TOOLS: "tools",
  PROFILE_SCREEN_ART: "art",
  PROFILE_SCREEN_GALLERIES: "galleries",
  ARTIST_CAMERAS: "cameras",
  ARTIST_LENS: "lens",
};
