export default {
  ARTIST_FIRSTNAME: "firstName",
  ARTIST_LASTNAME: "lastName",
  ARTIST_USERNAME: "username",
  ARTIST_DISPLAYNAME: "displayName",
  ARTIST_LOCATION: "location",
  ARTIST_EMAIL: "email",
  ARTIST_PHONE: "phone",
  ARTIST_ABOUT: "about",
  ARTIST_ARTTYPE: "artType",
  UPDATE_ARTIST_SCREEN_USER: "artist",
  UPDATE_ARTIST_SCREEN_TOOLS: "tools",
  PROFILE_SCREEN_ART: "art",
  PROFILE_SCREEN_SERVICES: "services",
  PROFILE_SCREEN_COLLECTIONS: "collections",
  PROFILE_SCREEN_GALLERIES: "galleries",
  COLLECTION_SCREEN_NFTS: "nfts",
  COLLECTION_SCREEN_DETAILS: "details",
  COLLECTION_SCREEN_CONSUMER: "consumerDetails",
  ARTIST_CAMERAS: "cameras",
  ARTIST_LENS: "lens",
  ARTIST_CANISTERID: "canisterId",
  ARTIST_ASSETCANISTERID: "assetCanId",
  ENTER_KEY_CODE: "Enter",
  ASSET_CANISTER_ID_ARTIST: "rno2w-sqaaa-aaaaa-aaacq-cai",
  ASSET_CANISTER_ID_SOCIALS: "r7inp-6aaaa-aaaaa-aaabq-cai",
};
